POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email":"test@gmail.com",
  "username":"sammy",
  "password":"@Sammy*12"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username":"sammy",
  "password":"@Sammy*12"
}